/**
 * 中国一级学科分类常量
 * 与后端 backend/app/constants.py 保持一致
 * 存储值格式："{code}-{name}"，如 "520-计算机科学技术"
 */
export const DISCIPLINES = [
  { code: '110', name: '数学' },
  { code: '120', name: '信息科学与系统科学' },
  { code: '130', name: '力学' },
  { code: '140', name: '物理学' },
  { code: '150', name: '化学' },
  { code: '160', name: '天文学' },
  { code: '170', name: '地球科学' },
  { code: '180', name: '生物学' },
  { code: '190', name: '心理学' },
  { code: '210', name: '农学' },
  { code: '220', name: '林学' },
  { code: '230', name: '畜牧、兽医科学' },
  { code: '240', name: '水产学' },
  { code: '310', name: '基础医学' },
  { code: '320', name: '临床医学' },
  { code: '330', name: '预防医学与公共卫生学' },
  { code: '340', name: '军事医学与特种医学' },
  { code: '350', name: '药学' },
  { code: '360', name: '中医学与中药学' },
  { code: '410', name: '工程与技术科学基础学科' },
  { code: '413', name: '信息与系统科学相关工程与技术' },
  { code: '416', name: '自然科学相关工程与技术' },
  { code: '420', name: '测绘科学技术' },
  { code: '430', name: '材料科学' },
  { code: '440', name: '矿山工程技术' },
  { code: '450', name: '冶金工程技术' },
  { code: '460', name: '机械工程' },
  { code: '470', name: '动力与电气工程' },
  { code: '480', name: '能源科学技术' },
  { code: '490', name: '核科学技术' },
  { code: '510', name: '电子与通信技术' },
  { code: '520', name: '计算机科学技术' },
  { code: '530', name: '化学工程' },
  { code: '535', name: '产品应用相关工程与技术' },
  { code: '540', name: '纺织科学技术' },
  { code: '550', name: '食品科学技术' },
  { code: '560', name: '土木建筑工程' },
  { code: '570', name: '水利工程' },
  { code: '580', name: '交通运输工程' },
  { code: '590', name: '航空、航天科学技术' },
  { code: '610', name: '环境科学技术及资源科学技术' },
  { code: '620', name: '安全科学技术' },
  { code: '630', name: '管理学' },
  { code: '710', name: '马克思主义' },
  { code: '720', name: '哲学' },
  { code: '730', name: '宗教学' },
  { code: '740', name: '语言学' },
  { code: '750', name: '文学' },
  { code: '760', name: '艺术学' },
  { code: '770', name: '历史学' },
  { code: '780', name: '考古学' },
  { code: '790', name: '经济学' },
  { code: '810', name: '政治学' },
  { code: '820', name: '法学' },
  { code: '830', name: '军事学' },
  { code: '840', name: '社会学' },
  { code: '850', name: '民族学与文化学' },
  { code: '860', name: '新闻学与传播学' },
  { code: '870', name: '图书馆、情报与文献学' },
  { code: '880', name: '教育学' },
  { code: '890', name: '体育科学' },
  { code: '910', name: '统计学' },
].map(d => ({ ...d, value: `${d.code}-${d.name}`, label: `${d.code} ${d.name}` }))

/**
 * 支持的论文原文语言（外文，不含中文）
 * disabled=true 表示计划中、尚未支持
 */
export const SUPPORTED_LANGUAGES = [
  { code: 'en', label: '英文',       disabled: false },
  { code: 'fr', label: '法文',       disabled: true },
  { code: 'de', label: '德文',       disabled: true },
  { code: 'ja', label: '日文',       disabled: true },
  { code: 'ko', label: '韩文',       disabled: true },
  { code: 'es', label: '西班牙文',   disabled: true },
  { code: 'ru', label: '俄文',       disabled: true },
  { code: 'ar', label: '阿拉伯文',   disabled: true },
  { code: 'pt', label: '葡萄牙文',   disabled: true },
  { code: 'it', label: '意大利文',   disabled: true },
]
