"""add_title_zh_domain_domain_glossary

Revision ID: 056447bed8d0
Revises: 55d3d9bca884
Create Date: 2026-04-06 00:40:36.707203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '056447bed8d0'
down_revision: Union[str, None] = '55d3d9bca884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_glossaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('en_term', sa.String(length=300), nullable=False),
    sa.Column('zh_term', sa.String(length=300), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain', 'en_term', name='uq_domain_term')
    )
    op.create_index(op.f('ix_domain_glossaries_domain'), 'domain_glossaries', ['domain'], unique=False)
    op.add_column('papers', sa.Column('title_zh', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('domain', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'domain')
    op.drop_column('papers', 'title_zh')
    op.drop_index(op.f('ix_domain_glossaries_domain'), table_name='domain_glossaries')
    op.drop_table('domain_glossaries')
    # ### end Alembic commands ###
