"""init

Revision ID: 55d3d9bca884
Revises: 
Create Date: 2026-04-05 00:37:11.994574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55d3d9bca884'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation_votes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('annotation_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('vote', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('annotation_id', 'user_id', name='uq_annotation_vote')
    )
    op.create_index(op.f('ix_annotation_votes_annotation_id'), 'annotation_votes', ['annotation_id'], unique=False)
    op.create_table('annotations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('result_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('block_id', sa.String(length=100), nullable=True),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('selected_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotations_result_id'), 'annotations', ['result_id'], unique=False)
    op.create_index(op.f('ix_annotations_user_id'), 'annotations', ['user_id'], unique=False)
    op.create_table('credit_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transactions_user_id'), 'credit_transactions', ['user_id'], unique=False)
    op.create_table('job_glossary_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('glossary_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_glossary_snapshots_job_id'), 'job_glossary_snapshots', ['job_id'], unique=True)
    op.create_table('papers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('uploader_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('authors', sa.JSON(), nullable=True),
    sa.Column('corresponding_author_email', sa.String(length=255), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('abstract_zh', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('doi', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('paper_type', sa.String(length=20), nullable=True),
    sa.Column('journal', sa.String(length=300), nullable=True),
    sa.Column('division', sa.String(length=100), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('structure_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_doi'), 'papers', ['doi'], unique=False)
    op.create_index(op.f('ix_papers_uploader_id'), 'papers', ['uploader_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('result_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('novelty', sa.SmallInteger(), nullable=True),
    sa.Column('rigor', sa.SmallInteger(), nullable=True),
    sa.Column('reproducibility', sa.SmallInteger(), nullable=True),
    sa.Column('impact', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('result_id', 'user_id', name='uq_result_review')
    )
    op.create_index(op.f('ix_reviews_result_id'), 'reviews', ['result_id'], unique=False)
    op.create_table('translation_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('current_stage', sa.String(length=100), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('queue_position', sa.Integer(), nullable=True),
    sa.Column('credits_cost', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('new_terms_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_jobs_paper_id'), 'translation_jobs', ['paper_id'], unique=False)
    op.create_index(op.f('ix_translation_jobs_user_id'), 'translation_jobs', ['user_id'], unique=False)
    op.create_table('translation_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('structure_json', sa.JSON(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_results_job_id'), 'translation_results', ['job_id'], unique=True)
    op.create_index(op.f('ix_translation_results_paper_id'), 'translation_results', ['paper_id'], unique=False)
    op.create_index(op.f('ix_translation_results_user_id'), 'translation_results', ['user_id'], unique=False)
    op.create_table('user_glossaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('en_term', sa.String(length=300), nullable=False),
    sa.Column('zh_term', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('source_job_id', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'en_term', name='uq_user_term')
    )
    op.create_index(op.f('ix_user_glossaries_user_id'), 'user_glossaries', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_glossaries_user_id'), table_name='user_glossaries')
    op.drop_table('user_glossaries')
    op.drop_index(op.f('ix_translation_results_user_id'), table_name='translation_results')
    op.drop_index(op.f('ix_translation_results_paper_id'), table_name='translation_results')
    op.drop_index(op.f('ix_translation_results_job_id'), table_name='translation_results')
    op.drop_table('translation_results')
    op.drop_index(op.f('ix_translation_jobs_user_id'), table_name='translation_jobs')
    op.drop_index(op.f('ix_translation_jobs_paper_id'), table_name='translation_jobs')
    op.drop_table('translation_jobs')
    op.drop_index(op.f('ix_reviews_result_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_papers_uploader_id'), table_name='papers')
    op.drop_index(op.f('ix_papers_doi'), table_name='papers')
    op.drop_table('papers')
    op.drop_index(op.f('ix_job_glossary_snapshots_job_id'), table_name='job_glossary_snapshots')
    op.drop_table('job_glossary_snapshots')
    op.drop_index(op.f('ix_credit_transactions_user_id'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index(op.f('ix_annotations_user_id'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_result_id'), table_name='annotations')
    op.drop_table('annotations')
    op.drop_index(op.f('ix_annotation_votes_annotation_id'), table_name='annotation_votes')
    op.drop_table('annotation_votes')
    # ### end Alembic commands ###
