"""add_translate_images_to_job

Revision ID: 72cab0dfd7c6
Revises: 59f9bd560e3d
Create Date: 2026-04-11 17:25:12.563412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72cab0dfd7c6'
down_revision: Union[str, None] = '59f9bd560e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translation_jobs', sa.Column('translate_images', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translation_jobs', 'translate_images')
    # ### end Alembic commands ###
